  Running command git clone --quiet https://github.com/huggingface/peft.git /tmp/pip-install-d704yua_/peft_4c19becfca24489e901c3e57e0ee0d42
  Running command git clone --quiet https://github.com/huggingface/accelerate.git /tmp/pip-install-d704yua_/accelerate_2b814f3ca2734f518aa44ee3b3fc818a
/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/getpass.py:91: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
Token: Traceback (most recent call last):
  File "/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/getpass.py", line 69, in unix_getpass
    old = termios.tcgetattr(fd)     # a copy to save
termios.error: (25, 'Inappropriate ioctl for device')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/sfs/weka/scratch/brc4cb/llama2-70b/qlora.py", line 57, in <module>
    login(token=token)
  File "/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages/huggingface_hub/_login.py", line 100, in login
    interpreter_login(new_session=new_session, write_permission=write_permission)
  File "/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages/huggingface_hub/_login.py", line 161, in interpreter_login
    token = getpass("Token: ")
  File "/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/getpass.py", line 91, in unix_getpass
    passwd = fallback_getpass(prompt, stream)
  File "/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/getpass.py", line 126, in fallback_getpass
    return _raw_input(prompt, stream)
  File "/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/getpass.py", line 148, in _raw_input
    raise EOFError
EOFError
