

==> WARNING: A newer version of conda exists. <==
  current version: 23.5.2
  latest version: 23.11.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.11.0


WARNING: Ignoring invalid distribution -riton-nightly (/sfs/qumulo/qhome/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages)
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/peft.git /tmp/pip-install-_5welczm/peft_7e524bef91b54323aff949175c86d675
  Running command git clone --filter=blob:none --quiet https://github.com/huggingface/accelerate.git /tmp/pip-install-_5welczm/accelerate_d7bb945080ee41fe9932c7e621583d9f
ERROR: Cannot install -r requirements.txt (line 2), -r requirements.txt (line 3), -r requirements.txt (line 6) and huggingface_hub==0.16.4 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
WARNING: Ignoring invalid distribution -riton-nightly (/sfs/qumulo/qhome/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages)
WARNING: Ignoring invalid distribution -riton-nightly (/sfs/qumulo/qhome/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages)


==> WARNING: A newer version of conda exists. <==
  current version: 23.5.2
  latest version: 23.11.0

Please update conda by running

    $ conda update -n base -c defaults conda

Or to minimize the number of packages updated during conda update use

     conda install conda=23.11.0


Loading checkpoint shards:   0%|          | 0/15 [00:00<?, ?it/s]Loading checkpoint shards:   7%|▋         | 1/15 [00:02<00:39,  2.79s/it]Loading checkpoint shards:  13%|█▎        | 2/15 [00:05<00:35,  2.72s/it]Loading checkpoint shards:  20%|██        | 3/15 [00:08<00:31,  2.67s/it]Loading checkpoint shards:  27%|██▋       | 4/15 [00:10<00:29,  2.65s/it]Loading checkpoint shards:  33%|███▎      | 5/15 [00:13<00:26,  2.65s/it]Loading checkpoint shards:  40%|████      | 6/15 [00:15<00:23,  2.64s/it]Loading checkpoint shards:  47%|████▋     | 7/15 [00:18<00:21,  2.68s/it]Loading checkpoint shards:  53%|█████▎    | 8/15 [00:21<00:18,  2.70s/it]Loading checkpoint shards:  60%|██████    | 9/15 [00:24<00:16,  2.70s/it]Loading checkpoint shards:  67%|██████▋   | 10/15 [00:26<00:13,  2.70s/it]Loading checkpoint shards:  73%|███████▎  | 11/15 [00:29<00:10,  2.73s/it]Loading checkpoint shards:  80%|████████  | 12/15 [00:32<00:08,  2.77s/it]Loading checkpoint shards:  87%|████████▋ | 13/15 [00:35<00:05,  2.71s/it]Loading checkpoint shards:  93%|█████████▎| 14/15 [00:37<00:02,  2.65s/it]Loading checkpoint shards: 100%|██████████| 15/15 [00:37<00:00,  1.92s/it]Loading checkpoint shards: 100%|██████████| 15/15 [00:37<00:00,  2.52s/it]
/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages/transformers/utils/hub.py:374: FutureWarning: The `use_auth_token` argument is deprecated and will be removed in v5 of Transformers.
  warnings.warn(
Traceback (most recent call last):
  File "/sfs/weka/scratch/brc4cb/llama2-70b/perplexity.py", line 78, in <module>
    df = pd.read_csv('data/all_models.csv')
  File "/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 912, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 577, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1407, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1661, in _make_engine
    self.handles = get_handle(
  File "/home/brc4cb/.conda/envs/falcon_40B/lib/python3.9/site-packages/pandas/io/common.py", line 859, in get_handle
    handle = open(
FileNotFoundError: [Errno 2] No such file or directory: 'data/all_models.csv'
